from decimal import Decimal
from datetime import timedelta
from dataclasses import replace
from types import SimpleNamespace
import pytest
from app.validation.protocol import split, bootstrap, verdict, historical_state
from app.backtesting.engine import simulate, simulate_rows
from app.features.engine import compute
from app.features.registry import STANDARD
from app.features.serialization import serialize
from app.strategies.dsl import digest
from app.market_data.timeframe import duration
from backtest_fixture import definition, config, candles, BASE
from validation_fixture import data, request


def test_exact_split_and_folds():
    rows = data(100)
    p = split(rows, BASE, rows[-1].close_time)
    assert p[:3] == [
        ("TRAIN", 0, BASE, rows[60].open_time),
        ("VALIDATION", 0, rows[60].open_time, rows[80].open_time),
        ("TEST", 0, rows[80].open_time, rows[-1].close_time),
    ]
    assert [(a, b) for _, _, a, b in p[3:]] == [(rows[i].open_time, rows[i + 5].open_time) for i in range(60, 80, 5)]
    with pytest.raises(ValueError):
        split(rows[:19], BASE, rows[-1].close_time)


@pytest.mark.parametrize("overlap", ["ALLOW", "SKIP_UNTIL_EXPIRY"])
@pytest.mark.parametrize("expiry", [1, 5, 60])
def test_refactor_exact_equivalence_and_no_partition_leakage(overlap, expiry):
    rows = data(200)
    d = definition(specs=STANDARD)
    cfg = request(200, expiry_bars=expiry, overlap_policy=overlap).child(BASE, rows[120].open_time, 200)
    a = simulate(rows, d, cfg)
    b = simulate_rows(list(compute(rows[:120], d.indicator_specs)), d, cfg, lambda: duration("1h"))
    for key in ["trades", "metrics", "equity_curve"]:
        assert a[key] == b[key]
    # Captured from the unmodified v0.5.0 engine, not generated by the refactored loop.
    golden = {
        (1, "ALLOW"): "13eae92462bf8cd7f8195092a7941c0b5df0b96cce9ffd7521ed84f03876dc68",
        (1, "SKIP_UNTIL_EXPIRY"): "13eae92462bf8cd7f8195092a7941c0b5df0b96cce9ffd7521ed84f03876dc68",
        (5, "ALLOW"): "3ccb4095c8bea5f08c015baaa79ef3f7ff84086a37945b29af44c6f860c937c8",
        (5, "SKIP_UNTIL_EXPIRY"): "05806ee65cc3b9c800d4827d0cd797ca22b7990ac842f70991db01aa163b8e7f",
        (60, "ALLOW"): "6671429d0a9db85b27b9f17963e5229bf05e5b2b416a19c07b441305b4f32f4d",
        (60, "SKIP_UNTIL_EXPIRY"): "ec33cc8c39511672844792790e116f1e8a33911ee8323893d03b457d1b6b194a",
    }
    assert digest(serialize({k: a[k] for k in ["trades", "metrics", "equity_curve"]})) == golden[expiry, overlap]
    assert all(t["expiry_time"] <= rows[120].open_time and t["expiry_candle_id"] <= 120 for t in b["trades"])
    mutated = rows[:120] + [replace(c, close=Decimal(500), high=Decimal(501)) for c in rows[120:]]
    assert simulate(mutated, d, cfg)["trades"] == a["trades"]


def test_original_req005_golden_output():
    result = simulate(candles(), definition(), config())
    assert [t["unit_pnl"] for t in result["trades"]] == [Decimal(".835"), Decimal("-1"), Decimal(0), Decimal("-1"), Decimal(".835")]
    assert result["metrics"]["total_unit_pnl"] == Decimal("-.33")


def test_bootstrap_manual_blocks_and_determinism():
    trades = [
        dict(signal_time=BASE, unit_pnl=Decimal(1)),
        dict(signal_time=BASE, unit_pnl=Decimal(1)),
        dict(signal_time=BASE + timedelta(days=1), unit_pnl=Decimal(-1)),
    ]
    a = bootstrap(trades, "a" * 64)
    assert a == bootstrap(trades, "a" * 64)
    assert a["block_count"] == 2 and a["iterations"] == 2000
    assert a["lower_95"] == -1 and a["upper_95"] == 1
    assert str(a["point_estimate"]).startswith("0.333333333333333333")
    assert bootstrap([], "a" * 64)["lower_95"] is None


def test_verdict_precedence_and_every_gate():
    m = dict(resolved_trades=100, total_unit_pnl="10", edge_percentage_points="1")
    folds = [m] * 4
    b = dict(block_count=10, lower_95=".1")
    assert verdict(m, folds, m, b)[0] == "PASS"
    assert verdict(m, folds, {**m, "total_unit_pnl": "-10"}, b)[0] == "FAIL"
    assert verdict(m, folds, {**m, "resolved_trades": 99, "total_unit_pnl": "-10"}, b)[0] == "INCONCLUSIVE"
    assert verdict(m, folds[:2], m, b)[0] == "INCONCLUSIVE"
    assert verdict(m, folds, m, {**b, "block_count": 9})[0] == "INCONCLUSIVE"
    assert verdict(m, folds, m, {**b, "lower_95": "0"})[0] == "FAIL"
    assert verdict({**m, "edge_percentage_points": "0"}, folds, m, b)[0] == "FAIL"
    assert verdict(m, [{**m, "total_unit_pnl": "0"}] * 2 + folds[:2], m, b)[0] == "FAIL"


def test_state_chronology_inconclusive_and_replay():
    def run(i, v):
        return SimpleNamespace(
            id=i,
            status="COMPLETED",
            verdict=v,
            test_start=BASE + timedelta(days=i),
            test_end=BASE + timedelta(days=i + 1),
            created_at=BASE,
            config_sha256=str(i),
        )

    assert historical_state([run(1, "FAIL")]) == "NOT_VALIDATED"
    assert historical_state([run(2, "INCONCLUSIVE"), run(1, "PASS")]) == "HISTORICALLY_VALIDATED"
    assert historical_state([run(3, "FAIL"), run(1, "PASS"), run(2, "INCONCLUSIVE")]) == "DEGRADED"
    assert historical_state([run(3, "FAIL"), run(1, "PASS"), run(4, "PASS")]) == "HISTORICALLY_VALIDATED"
