from alembic import op
import sqlalchemy as sa

revision = '001_initial'; down_revision = None; branch_labels = None; depends_on = None
def upgrade():
    op.create_table('users', sa.Column('id', sa.Integer, primary_key=True), sa.Column('email', sa.String(320), nullable=False, unique=True), sa.Column('password_hash', sa.String(255), nullable=False), sa.Column('name', sa.String(120), nullable=False), sa.Column('role', sa.String(20), nullable=False, server_default='USER'), sa.Column('status', sa.String(20), nullable=False, server_default='ACTIVE'), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('trading_accounts', sa.Column('id', sa.Integer, primary_key=True), sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False), sa.Column('name', sa.String(120), nullable=False), sa.Column('broker', sa.String(120)), sa.Column('currency', sa.String(3), nullable=False, server_default='USD'), sa.Column('initial_balance', sa.Numeric(18, 8), nullable=False), sa.Column('current_balance', sa.Numeric(18, 8), nullable=False), sa.Column('status', sa.String(20), nullable=False, server_default='ACTIVE'), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('risk_profiles', sa.Column('id', sa.Integer, primary_key=True), sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False, unique=True), sa.Column('risk_per_trade_percent', sa.Numeric(8,4), nullable=False), sa.Column('max_session_loss_percent', sa.Numeric(8,4), nullable=False), sa.Column('max_session_operations', sa.Integer, nullable=False), sa.Column('minimum_payout_percent', sa.Numeric(8,4), nullable=False), sa.Column('profit_target_percent', sa.Numeric(8,4)), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('trading_sessions', sa.Column('id', sa.Integer, primary_key=True), sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False), sa.Column('trading_account_id', sa.Integer, sa.ForeignKey('trading_accounts.id'), nullable=False), sa.Column('started_at', sa.DateTime(timezone=True), nullable=False), sa.Column('ended_at', sa.DateTime(timezone=True)), sa.Column('starting_balance', sa.Numeric(18,8), nullable=False), sa.Column('ending_balance', sa.Numeric(18,8)), sa.Column('risk_per_trade_percent', sa.Numeric(8,4), nullable=False), sa.Column('max_loss_amount', sa.Numeric(18,8), nullable=False), sa.Column('profit_target_amount', sa.Numeric(18,8)), sa.Column('max_operations', sa.Integer, nullable=False), sa.Column('status', sa.String(20), nullable=False, server_default='OPEN'), sa.Column('notes', sa.Text), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('trades', sa.Column('id', sa.Integer, primary_key=True), sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False), sa.Column('trading_account_id', sa.Integer, sa.ForeignKey('trading_accounts.id'), nullable=False), sa.Column('trading_session_id', sa.Integer, sa.ForeignKey('trading_sessions.id'), nullable=False), sa.Column('source', sa.String(30), nullable=False, server_default='MANUAL'), sa.Column('symbol', sa.String(50), nullable=False), sa.Column('market_type', sa.String(20), nullable=False), sa.Column('timeframe', sa.String(20), nullable=False), sa.Column('direction', sa.String(10), nullable=False), sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False), sa.Column('expiration_at', sa.DateTime(timezone=True)), sa.Column('stake', sa.Numeric(18,8), nullable=False), sa.Column('payout_percent', sa.Numeric(8,4), nullable=False), sa.Column('result', sa.String(20)), sa.Column('profit_loss', sa.Numeric(18,8)), sa.Column('notes', sa.Text), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('account_ledger_entries', sa.Column('id', sa.Integer, primary_key=True), sa.Column('account_id', sa.Integer, sa.ForeignKey('trading_accounts.id'), nullable=False), sa.Column('trade_id', sa.Integer, sa.ForeignKey('trades.id')), sa.Column('session_id', sa.Integer, sa.ForeignKey('trading_sessions.id')), sa.Column('entry_type', sa.String(30), nullable=False), sa.Column('amount', sa.Numeric(18,8), nullable=False), sa.Column('balance_before', sa.Numeric(18,8), nullable=False), sa.Column('balance_after', sa.Numeric(18,8), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('metadata', sa.JSON))
    op.create_table('journal_entries', sa.Column('id', sa.Integer, primary_key=True), sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False), sa.Column('trade_id', sa.Integer, sa.ForeignKey('trades.id')), sa.Column('session_id', sa.Integer, sa.ForeignKey('trading_sessions.id')), sa.Column('title', sa.String(200), nullable=False), sa.Column('content', sa.Text, nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('audit_logs', sa.Column('id', sa.Integer, primary_key=True), sa.Column('user_id', sa.Integer, sa.ForeignKey('users.id'), nullable=False), sa.Column('event_type', sa.String(50), nullable=False), sa.Column('entity_type', sa.String(50), nullable=False), sa.Column('entity_id', sa.Integer), sa.Column('metadata', sa.JSON), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('candles', sa.Column('id', sa.Integer, primary_key=True), sa.Column('source', sa.String(50), nullable=False), sa.Column('broker', sa.String(120)), sa.Column('symbol', sa.String(50), nullable=False), sa.Column('market_type', sa.String(20), nullable=False), sa.Column('timeframe', sa.String(20), nullable=False), sa.Column('open_time', sa.DateTime(timezone=True), nullable=False), sa.Column('close_time', sa.DateTime(timezone=True), nullable=False), sa.Column('open', sa.Numeric(24,10), nullable=False), sa.Column('high', sa.Numeric(24,10), nullable=False), sa.Column('low', sa.Numeric(24,10), nullable=False), sa.Column('close', sa.Numeric(24,10), nullable=False), sa.Column('tick_volume', sa.Numeric(24,10)), sa.Column('spread', sa.Numeric(24,10)), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False), sa.UniqueConstraint('source','symbol','market_type','timeframe','open_time', name='uq_candle_identity'))
def downgrade():
    for t in ['candles','audit_logs','journal_entries','account_ledger_entries','trades','trading_sessions','risk_profiles','trading_accounts','users']: op.drop_table(t)
