import { test, expect } from '@playwright/test';

test('USER researches existing fixture with exact EMA/RSI and snapshot metadata', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/features');
  await page.getByLabel("Correo electrónico").fill('qa@example.com');
  await page.getByLabel("Contraseña").fill('browser-test-only');
  await page.getByRole('button', { name: "Iniciar sesión" }).click();
  await page.locator("aside").getByRole('link', { name: "Indicadores", exact: true }).click();
  await page.getByLabel("Conjunto de datos", { exact: true }).selectOption({ label: 'FEATURE_FIXTURE / DEMO / EURUSD / REGULAR / 1m' });
  await page.getByRole('button', { name: "Cargar conjunto estándar" }).click();
  const response = page.waitForResponse(r => r.url().endsWith('/features/compute'));
  await page.getByRole('button', { name: "Analizar", exact: true }).click();
  const result = await (await response).json();
  expect(result.rows[19].features.ema_20).toBe('10.5');
  expect(result.rows[99].features.ema_20).toBe('90.5');
  expect(result.rows[14].features.rsi_14).toBe('100');
  const results = page.getByRole('region', { name: "Resultados de indicadores" });
  await expect(results.getByText('cq-features-v1', { exact: true })).toBeVisible();
  await expect(results.getByText("ID de vela de corte", { exact: true })).toBeVisible();
  await expect(results.getByRole('cell', { name: '10.5', exact: true }).first()).toBeVisible();
  await expect(results.getByRole('cell', { name: '—', exact: true }).first()).toBeVisible();
  const chart = page.getByLabel("Gráfico de velas e indicadores");
  await expect(chart.locator('canvas').first()).toBeVisible();
  expect(await chart.locator('canvas').count()).toBeGreaterThanOrEqual(6);
  await chart.hover();
  await expect(page.getByLabel("Detalle de la vela")).toContainText('UTC');
  await page.screenshot({ path: 'test-results/req004-features-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 768, height: 1024 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/req004-features-tablet.png', fullPage: true });
  expect(errors).toEqual([]);
});
