import { test, expect } from "@playwright/test";
import path from "node:path";

test("ADMIN imports disposable deterministic candles and catalogs CCC without crossing gaps", async ({ page }) => {
  await page.goto("/login");
  await page.getByLabel("Correo electrónico").fill("market-admin@example.com");
  await page.getByLabel("Contraseña").fill("browser-test-only");
  await page.getByRole("button", { name: "Iniciar sesión" }).click();
  await page.locator("aside").getByRole("link", { name: "Datos de mercado", exact: true }).click();
  await page.getByLabel("Fuente", { exact: true }).fill("SYNTHETIC_QA");
  await page.getByLabel("Bróker", { exact: true }).fill("DEMO");
  await page.getByLabel("Símbolo", { exact: true }).fill("EURUSD");
  await page.getByLabel("Archivo CSV").setInputFiles(path.resolve("../examples/market_data/synthetic_regular.csv"));
  await page.getByRole("button", { name: "Revisar importación", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("synthetic_regular.csv");
  await page.getByRole("button", { name: "Confirmar importación" }).click();
  await expect(page.getByRole("heading", { name: "Importación Completada (COMPLETED)" })).toBeVisible();
  const report = page.getByRole("region", { name: "Informe de importación" });
  await expect(report.locator("div").filter({ has: page.locator("dt", { hasText: /^Insertadas$/ }) }).last()).toContainText("30");
  await page.getByRole("row").filter({ has: page.getByRole("cell", { name: "SYNTHETIC_QA", exact: true }) }).getByRole("button", { name: "Inspeccionar", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Inspección de velas" })).toBeVisible();
  await page.locator("aside").getByRole("link", { name: "Patrones de velas", exact: true }).click();
  await page.getByLabel("Conjunto de datos", { exact: true }).selectOption({ label: "SYNTHETIC_QA / DEMO / EURUSD / REGULAR / 1m" });
  await page.getByLabel("Longitud del patrón").selectOption("3");
  await page.getByRole("button", { name: "Analizar", exact: true }).click();
  const results = page.getByRole("region", { name: "Resultados del catálogo" });
  const row = results.getByRole("row").filter({ has: page.getByRole("cell", { name: "CCC", exact: true }) });
  await expect(row).toContainText("100.00%");
  const cells = row.getByRole("cell");
  await expect(cells.nth(1)).toContainText("6");
  await expect(cells.nth(2)).toHaveText("0");
  await expect(cells.nth(3)).toHaveText("6");
  await expect(cells.nth(4)).toHaveText("0");
  await expect(results.locator("div").filter({ has: page.locator("dt", { hasText: "Ventanas omitidas por huecos" }) }).last()).toContainText("3");
  await page.screenshot({ path: "test-results/req003-cataloger-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 768, height: 1024 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/req003-cataloger-tablet.png", fullPage: true });
  await page.locator("aside").getByRole("link", { name: "Datos de mercado", exact: true }).click();
  await page.screenshot({ path: "test-results/req003-market-data-tablet.png", fullPage: true });
});

