import {test,expect} from '@playwright/test';
test('USER builds immutable RSI/Bollinger research version and inspects causal unit outcomes',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/login');
  await page.getByLabel("Correo electrónico").fill('qa@example.com');await page.getByLabel("Contraseña").fill('browser-test-only');
  await page.getByRole('button',{name:"Iniciar sesión"}).click();
  await page.locator("aside").getByRole('link',{name:"Estrategias",exact:true}).click();
  await page.getByLabel("Nombre",{exact:true}).fill('Research Example — binary fixture');
  await page.getByLabel("Descripción").fill('Disposable manual fixture, not validated');
  await page.getByRole('button',{name:"Crear estrategia",exact:true}).click();
  await page.getByRole('link',{name:'Research Example — binary fixture',exact:true}).first().click();
  await page.getByRole('button',{name:"Añadir indicador",exact:true}).click();
  await page.getByRole('combobox',{name:"Indicador 1",exact:true}).selectOption('RSI');
  await page.getByLabel("Período 1",{exact:true}).fill('2');
  await page.getByRole('button',{name:"Añadir indicador",exact:true}).click();
  await page.getByRole('combobox',{name:"Indicador 2",exact:true}).selectOption('BOLLINGER');
  await page.getByLabel("Período 2",{exact:true}).fill('2');
  await page.getByRole('combobox',{name:"Campo 1",exact:true}).selectOption('rsi_2');
  await page.getByRole('combobox',{name:"Operador 1",exact:true}).selectOption('GTE');
  await page.getByLabel("Valor 1",{exact:true}).fill('0');
  await page.getByRole('button',{name:"Añadir condición",exact:true}).click();
  await page.getByRole('combobox',{name:"Operador 2",exact:true}).selectOption('LTE');
  await page.getByRole('combobox',{name:"Tipo de operando 2",exact:true}).selectOption('FIELD');
  await page.getByRole('combobox',{name:"Campo derecho 2",exact:true}).selectOption('bb_upper_2_2');
  await page.getByRole('button',{name:"Crear versión",exact:true}).click();
  await page.getByRole('button',{name:"Probar históricamente v1",exact:true}).click();
  await page.getByRole('combobox',{name:"Conjunto de datos",exact:true}).selectOption({label:'BINARY_FIXTURE / DEMO / EURUSD / REGULAR / 1m'});
  await page.getByLabel("Fin exclusivo de señales (con zona horaria)").fill('2026-01-01T00:06:00Z');
  await page.getByLabel("Rendimiento %",{exact:true}).fill('83.5');
  const response=page.waitForResponse(r=>r.url().endsWith('/backtests')&&r.request().method()==='POST');
  await page.getByRole('button',{name:"Iniciar prueba histórica",exact:true}).click();
  const result=await(await response).json();
  expect(result.status).toBe('COMPLETED');expect(result.metrics.total_unit_pnl).toBe('-0.165');
  expect(result.metrics.trades_executed).toBe(3);expect(result.metrics.skipped_unavailable).toBe(2);
  await expect(page).toHaveURL(/backtests\/\d+/);
  await expect(page.getByText(/DENTRO DE LA MUESTRA · SIN VALIDAR/)).toBeVisible();
  await expect(page.getByText(/Supuesto de rendimiento fijo: 83.5%/)).toBeVisible();
  await expect(page.getByRole('img',{name:"Curva de resultado acumulado en unidades"})).toBeVisible();
  await expect(page.getByRole('cell',{name:'0.835',exact:true})).toBeVisible();
  await page.getByRole('button',{name:"Inspeccionar n.º3",exact:true}).click();
  await expect(page.getByRole('region',{name:"Contexto de señal"})).toContainText('rsi_2@0');
  await page.screenshot({path:'test-results/req005-backtest-desktop.png',fullPage:true});
  await page.setViewportSize({width:768,height:1024});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/req005-backtest-tablet.png',fullPage:true});
  expect(errors).toEqual([]);
});
