import {test,expect} from '@playwright/test';
test('USER builds immutable RSI/Bollinger research version and inspects causal unit outcomes',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/login');
  await page.getByLabel('Email').fill('qa@example.com');await page.getByLabel('Password').fill('browser-test-only');
  await page.getByRole('button',{name:'Sign in'}).click();
  await page.getByRole('link',{name:'Strategy Lab',exact:true}).click();
  await page.getByLabel('Name',{exact:true}).fill('Research Example — binary fixture');
  await page.getByLabel('Description').fill('Disposable manual fixture, not validated');
  await page.getByRole('button',{name:'Create strategy',exact:true}).click();
  await page.getByRole('link',{name:'Research Example — binary fixture',exact:true}).first().click();
  await page.getByRole('button',{name:'Add indicator',exact:true}).click();
  await page.getByRole('combobox',{name:'Indicator 1',exact:true}).selectOption('RSI');
  await page.getByLabel('Period 1',{exact:true}).fill('2');
  await page.getByRole('button',{name:'Add indicator',exact:true}).click();
  await page.getByRole('combobox',{name:'Indicator 2',exact:true}).selectOption('BOLLINGER');
  await page.getByLabel('Period 2',{exact:true}).fill('2');
  await page.getByRole('combobox',{name:'Field 1',exact:true}).selectOption('rsi_2');
  await page.getByRole('combobox',{name:'Operator 1',exact:true}).selectOption('GTE');
  await page.getByLabel('Value 1',{exact:true}).fill('0');
  await page.getByRole('button',{name:'Add condition',exact:true}).click();
  await page.getByRole('combobox',{name:'Operator 2',exact:true}).selectOption('LTE');
  await page.getByRole('combobox',{name:'Operand type 2',exact:true}).selectOption('FIELD');
  await page.getByRole('combobox',{name:'Right field 2',exact:true}).selectOption('bb_upper_2_2');
  await page.getByRole('button',{name:'Create version',exact:true}).click();
  await page.getByRole('button',{name:'Run Backtest v1',exact:true}).click();
  await page.getByRole('combobox',{name:'Dataset',exact:true}).selectOption({label:'BINARY_FIXTURE / DEMO / EURUSD / REGULAR / 1m'});
  await page.getByLabel('Signal end exclusive (timezone required)').fill('2026-01-01T00:06:00Z');
  await page.getByLabel('Payout %',{exact:true}).fill('83.5');
  const response=page.waitForResponse(r=>r.url().endsWith('/backtests')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Start backtest',exact:true}).click();
  const result=await(await response).json();
  expect(result.status).toBe('COMPLETED');expect(result.metrics.total_unit_pnl).toBe('-0.165');
  expect(result.metrics.trades_executed).toBe(3);expect(result.metrics.skipped_unavailable).toBe(2);
  await expect(page).toHaveURL(/backtests\/\d+/);
  await expect(page.getByText(/IN-SAMPLE · NOT VALIDATED/)).toBeVisible();
  await expect(page.getByText(/Fixed payout assumption: 83.5%/)).toBeVisible();
  await expect(page.getByRole('img',{name:'Unit Equity Curve'})).toBeVisible();
  await expect(page.getByRole('cell',{name:'0.835',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Inspect #3',exact:true}).click();
  await expect(page.getByRole('region',{name:'Signal context'})).toContainText('rsi_2@0');
  await page.screenshot({path:'test-results/req005-backtest-desktop.png',fullPage:true});
  await page.setViewportSize({width:768,height:1024});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/req005-backtest-tablet.png',fullPage:true});
  expect(errors).toEqual([]);
});
