import {test,expect} from '@playwright/test';
test('exact research workspace links manual, validation, Replay and paper evidence',async({page})=>{
 await page.goto('/login');await page.getByLabel("Correo electrónico").fill('qa@example.com');await page.getByLabel("Contraseña").fill('browser-test-only');await page.getByRole('button',{name:"Iniciar sesión"}).click();
 await expect(page.locator("aside").getByRole('link',{name:"Área de investigación",exact:true})).toBeVisible();
 const base='http://localhost:8010/api/v1';
 const strategies=await (await page.request.get(base+'/strategies')).json();
 const strategy=strategies.items.find((s:{name:string})=>s.name==='Scanner validated fixture');
 const version=strategy.latest_version.id;
 const dataset={source:'SCANNER_FIXTURE',broker:'DEMO',symbol:'EURUSD',market_type:'REGULAR',timeframe:'1h'};
 const run=await page.request.post(base+'/backtests',{data:{strategy_version_id:version,dataset,signal_start:'2026-01-01T00:00:00Z',signal_end:'2026-03-04T12:00:00Z',payout_percent:'83.5',expiry_bars:1}});
 expect(run.ok()).toBeTruthy();const manual=await run.json();expect(manual.status).toBe('COMPLETED');
 const watch=await (await page.request.post(base+'/scanner/watchlists',{data:{name:'Workspace E2E'}})).json();
 expect((await page.request.post(base+`/scanner/watchlists/${watch.id}/items`,{data:{provider:'REPLAY',dataset,strategy_version_id:version,research_mode:true,research_payout:'84',research_expiry:1}})).ok()).toBeTruthy();
 await page.locator("aside").getByRole('link',{name:"Área de investigación",exact:true}).click();
 await page.getByLabel("Datos del área de investigación").selectOption({label:'SCANNER_FIXTURE / DEMO / EURUSD / REGULAR / 1h'});
 await page.getByLabel("Estrategia del área de investigación").selectOption(String(strategy.id));await page.getByLabel("Versión del área de investigación").selectOption(String(version));
 await expect(page.getByRole('list',{name:"Etapas de investigación"})).toBeVisible();
 await expect(page.getByText("Última prueba histórica manual:",{exact:false})).toBeVisible();
 await expect(page.getByRole('link',{name:'Validación (VALIDATION)',exact:true})).toHaveAttribute('href',/\/validation\/\d+/);
 await page.screenshot({path:'test-results/req008-workspace-desktop.png',fullPage:true});
 await page.setViewportSize({width:768,height:1024});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/req008-workspace-tablet.png',fullPage:true});
 await expect.poll(async()=> (await (await page.request.get(base+'/workspace/events?'+new URLSearchParams({...dataset,strategy_version_id:String(version)}))).json()).total).toBeGreaterThan(0);
 await page.reload();await page.getByLabel("Datos del área de investigación").selectOption({label:'SCANNER_FIXTURE / DEMO / EURUSD / REGULAR / 1h'});await page.getByLabel("Estrategia del área de investigación").selectOption(String(strategy.id));await page.getByLabel("Versión del área de investigación").selectOption(String(version));
 await page.getByRole('link',{name:/Evento n\.º/}).first().click();await expect(page.getByRole('heading',{name:/Trazabilidad de seguimiento y simulación/})).toBeVisible();
 await expect(page.getByText(/payout_source/)).toBeVisible();
});
